# Generated by Django 3.2.12 on 2023-02-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ico', models.ImageField(upload_to='redes_sociales')),
                ('nombre', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
